export const UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS'
export const UPDATE_ACCOUNT_NAME = 'UPDATE_ACCOUNT'
export const UPDATE_CONTAINERS = 'UPDATE_CONTAINERS'
export const UPDATE_CONTAINER = 'UPDATE_CONTAINER'
export const DELETE_CONTAINER = 'DELETE_CONTAINER'
export const UPDATE_TAGS = 'UPDATE_TAGS'
export const UPDATE_TAG = 'UPDATE_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const UPDATE_TRIGGERS = 'UPDATE_TRIGGERS'
export const UPDATE_TRIGGER = 'UPDATE_TRIGGER'
export const DELETE_TRIGGER = 'DELETE_TRIGGER'
export const UPDATE_VARIABLES = 'UPDATE_VARIABLES'
export const UPDATE_VARIABLE = 'UPDATE_VARIABLE'
export const DELETE_VARIABLE = 'DELETE_VARIABLE'

// export default {
//   UPDATE_ACCOUNTS,
//   UPDATE_ACCOUNT,
//   UPDATE_CONTAINERS,
//   UPDATE_CONTAINER,
//   DELETE_CONTAINER,
//   UPDATE_TAGS,
//   UPDATE_TAG,
//   DELETE_TAG,
//   UPDATE_TRIGGERS,
//   UPDATE_TRIGGER,
//   DELETE_TRIGGER,
//   UPDATE_VARIABLES,
//   UPDATE_VARIABLE,
//   DELETE_VARIABLE,
// }